version: "3.1"
services:

  nats:
    image: nats
    command: -js
    hostname: nats
    container_name: nats
    ports:
      - 4222:4222

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379